/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Encargo;
import controlador.Controller;

/**
 *
 * @author javi5454
 */
public class Vista extends javax.swing.JFrame {
    private static Controller c;
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }
    
    public Vista(Controller c){
        this.c = c;
        initComponents();
    }
    
    void setVista(Encargo e){
        lbClientText.setText(e.getCliente());
        lbCameraText.setText(e.getRealizacoCon().get(c.getCamaraActual()).getMarca());
        lbTypeText.setText(e.getRealizacoCon().get(c.getCamaraActual()).getType());
        repaint();
    }
    
    public void updateView(){
        setVista(c.getModelo());
    }
    
    public void showView(){
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSiguiente = new javax.swing.JButton();
        lbCamara = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbClientText = new javax.swing.JLabel();
        lbCameraText = new javax.swing.JLabel();
        lbTypeText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btSiguiente.setText("Siguiente Cámara");
        btSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSiguienteActionPerformed(evt);
            }
        });

        lbCamara.setText("Cámara:");

        lbCliente.setText("Cliente:");

        lbTipo.setText("Tipo:");

        lbClientText.setBackground(new java.awt.Color(0, 0, 0));
        lbClientText.setText("jLabel1");

        lbCameraText.setText("jLabel1");

        lbTypeText.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCamara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCameraText)
                        .addGap(75, 75, 75)
                        .addComponent(lbTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTypeText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbClientText))
                    .addComponent(btSiguiente))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCliente)
                    .addComponent(lbClientText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCamara)
                    .addComponent(lbTipo)
                    .addComponent(lbCameraText)
                    .addComponent(lbTypeText))
                .addGap(35, 35, 35)
                .addComponent(btSiguiente)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSiguienteActionPerformed
        c.next();
        updateView();
    }//GEN-LAST:event_btSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSiguiente;
    private javax.swing.JLabel lbCamara;
    private javax.swing.JLabel lbCameraText;
    private javax.swing.JLabel lbClientText;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTypeText;
    // End of variables declaration//GEN-END:variables
}
