#!/bin/bash
# Titulo: repaso
# Fecha: 13/4/2021
# Autor: Javier Gómez López
# Versión: 1.0
# Descripción: En la carpeta personal, construya un guión llamado repaso-guion que admita tres argumentos, el primero será un directorio, el segundo una letra, y el tercero una palabra.
# El guión debe: Comprobar que se le están pasando tres argumentos, y si no fuera así, indicar cómo se debe ejecutar para que funcione correctamente. Esto es, dar una pequeña ayuda y terminar.
# Crear, en caso de no existir, el directorio dado como primer argumento.
# Comprobar que el segundo argumento sea una f o una d. Si no fuera así, indicarlo con un mensaje de error y salir.
# Encontrar la palabra dada en el tercer argumento de forma recursiva en los archivos existentes a partir del directorio indicado por el usuario (primer argumento), incluyendo el número de línea en donde se localiza el término. 
# Almacenar el resultado de la consulta en un fichero llamado resultado dentro del directorio desde el que se ejecute el guión.
# Buscar en el directorio indicado por el usuario (primer argumento) todos los ficheros o directorios según la letra pasada como segundo argumento (f=fichero, d=directorio) 
#Almacenar el resultado de la consulta al final del fichero resultado del apartado anterior.
# Opciones: Dos argumentos

validate_number=^-?[0-9]+([.][0-9]+)?$; #creamos la expresion para validar los numeros

if [ $# != 3 ];
then 
    echo "Error de argumentos. <entero> <entero> <fichero>"
    exit 1
fi

if ![[ $1 =~ $validate_number ]] && ![[ $2 =~ $validate_number ]];
then
    echo "Error al ingresar los enteros"
    exit 1
fi